ALTER TABLE votes PARTITION BY RANGE(Id)  (
        PARTITION p0 VALUES LESS THAN (10000),
        PARTITION p1 VALUES LESS THAN (20000),
        PARTITION p2 VALUES LESS THAN (30000),
        PARTITION p3 VALUES LESS THAN MAXVALUE
);